/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiResponse,
  SettlementResultDtoApiResponse,
  ToggleSettledRequest,
} from "../../models";

import { customInstance } from "../../../shared/lib/axios-instance";

/**
 * @summary 計算帳單結算
 */
export const getApiSnapSplitBillsBillIdSettlement = (
  billId: string,
  signal?: AbortSignal,
) => {
  return customInstance<SettlementResultDtoApiResponse>({
    url: `/api/snap-split/bills/${billId}/settlement`,
    method: "GET",
    signal,
  });
};

export const getGetApiSnapSplitBillsBillIdSettlementQueryKey = (
  billId?: string,
) => {
  return [`/api/snap-split/bills/${billId}/settlement`] as const;
};

export const getGetApiSnapSplitBillsBillIdSettlementQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
  TError = ApiResponse,
>(
  billId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiSnapSplitBillsBillIdSettlementQueryKey(billId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>
  > = ({ signal }) => getApiSnapSplitBillsBillIdSettlement(billId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!billId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetApiSnapSplitBillsBillIdSettlementQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>
>;
export type GetApiSnapSplitBillsBillIdSettlementQueryError = ApiResponse;

export function useGetApiSnapSplitBillsBillIdSettlement<
  TData = Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
  TError = ApiResponse,
>(
  billId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
          TError,
          Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetApiSnapSplitBillsBillIdSettlement<
  TData = Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
  TError = ApiResponse,
>(
  billId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
          TError,
          Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetApiSnapSplitBillsBillIdSettlement<
  TData = Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
  TError = ApiResponse,
>(
  billId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary 計算帳單結算
 */

export function useGetApiSnapSplitBillsBillIdSettlement<
  TData = Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
  TError = ApiResponse,
>(
  billId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSnapSplitBillsBillIdSettlement>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetApiSnapSplitBillsBillIdSettlementQueryOptions(
    billId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 切換轉帳結清狀態
 */
export const postApiSnapSplitBillsBillIdSettlementToggle = (
  billId: string,
  toggleSettledRequest: ToggleSettledRequest,
  signal?: AbortSignal,
) => {
  return customInstance<void>({
    url: `/api/snap-split/bills/${billId}/settlement/toggle`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: toggleSettledRequest,
    signal,
  });
};

export const getPostApiSnapSplitBillsBillIdSettlementToggleMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdSettlementToggle>>,
    TError,
    { billId: string; data: ToggleSettledRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdSettlementToggle>>,
  TError,
  { billId: string; data: ToggleSettledRequest },
  TContext
> => {
  const mutationKey = ["postApiSnapSplitBillsBillIdSettlementToggle"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdSettlementToggle>>,
    { billId: string; data: ToggleSettledRequest }
  > = (props) => {
    const { billId, data } = props ?? {};

    return postApiSnapSplitBillsBillIdSettlementToggle(billId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiSnapSplitBillsBillIdSettlementToggleMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdSettlementToggle>>
  >;
export type PostApiSnapSplitBillsBillIdSettlementToggleMutationBody =
  ToggleSettledRequest;
export type PostApiSnapSplitBillsBillIdSettlementToggleMutationError =
  ApiResponse;

/**
 * @summary 切換轉帳結清狀態
 */
export const usePostApiSnapSplitBillsBillIdSettlementToggle = <
  TError = ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdSettlementToggle>>,
      TError,
      { billId: string; data: ToggleSettledRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdSettlementToggle>>,
  TError,
  { billId: string; data: ToggleSettledRequest },
  TContext
> => {
  const mutationOptions =
    getPostApiSnapSplitBillsBillIdSettlementToggleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
