/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiResponse,
  AuthResultDtoApiResponse,
  GetApiAuthGoogleUrlParams,
  GetApiAuthLineUrlParams,
  GoogleLoginRequestDto,
  LineLoginRequestDto,
  ObjectApiResponse,
  RefreshTokenRequestDto,
  UserDtoApiResponse,
} from "../../models";

import { axiosInstance } from "../../axios-instance";

/**
 * @summary 取得可用的登入方式
 */
export const getApiAuthProviders = (signal?: AbortSignal) => {
  return axiosInstance<ObjectApiResponse>({
    url: `/api/Auth/providers`,
    method: "GET",
    signal,
  });
};

export const getGetApiAuthProvidersQueryKey = () => {
  return [`/api/Auth/providers`] as const;
};

export const getGetApiAuthProvidersQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthProviders>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiAuthProviders>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthProvidersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAuthProviders>>
  > = ({ signal }) => getApiAuthProviders(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthProviders>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthProvidersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAuthProviders>>
>;
export type GetApiAuthProvidersQueryError = unknown;

export function useGetApiAuthProviders<
  TData = Awaited<ReturnType<typeof getApiAuthProviders>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthProviders>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthProviders>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthProviders>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthProviders<
  TData = Awaited<ReturnType<typeof getApiAuthProviders>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthProviders>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthProviders>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthProviders>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthProviders<
  TData = Awaited<ReturnType<typeof getApiAuthProviders>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthProviders>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 取得可用的登入方式
 */

export function useGetApiAuthProviders<
  TData = Awaited<ReturnType<typeof getApiAuthProviders>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthProviders>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAuthProvidersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 取得 LINE 登入 URL
 */
export const getApiAuthLineUrl = (
  params?: GetApiAuthLineUrlParams,
  signal?: AbortSignal,
) => {
  return axiosInstance<ObjectApiResponse>({
    url: `/api/Auth/line/url`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiAuthLineUrlQueryKey = (
  params?: GetApiAuthLineUrlParams,
) => {
  return [`/api/Auth/line/url`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuthLineUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthLineUrl>>,
  TError = ApiResponse,
>(
  params?: GetApiAuthLineUrlParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthLineUrl>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiAuthLineUrlQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAuthLineUrl>>
  > = ({ signal }) => getApiAuthLineUrl(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthLineUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthLineUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAuthLineUrl>>
>;
export type GetApiAuthLineUrlQueryError = ApiResponse;

export function useGetApiAuthLineUrl<
  TData = Awaited<ReturnType<typeof getApiAuthLineUrl>>,
  TError = ApiResponse,
>(
  params: undefined | GetApiAuthLineUrlParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthLineUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthLineUrl>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthLineUrl>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthLineUrl<
  TData = Awaited<ReturnType<typeof getApiAuthLineUrl>>,
  TError = ApiResponse,
>(
  params?: GetApiAuthLineUrlParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthLineUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthLineUrl>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthLineUrl>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthLineUrl<
  TData = Awaited<ReturnType<typeof getApiAuthLineUrl>>,
  TError = ApiResponse,
>(
  params?: GetApiAuthLineUrlParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthLineUrl>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 取得 LINE 登入 URL
 */

export function useGetApiAuthLineUrl<
  TData = Awaited<ReturnType<typeof getApiAuthLineUrl>>,
  TError = ApiResponse,
>(
  params?: GetApiAuthLineUrlParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthLineUrl>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAuthLineUrlQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary LINE 登入回呼
 */
export const postApiAuthLineCallback = (
  lineLoginRequestDto: LineLoginRequestDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<AuthResultDtoApiResponse>({
    url: `/api/Auth/line/callback`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: lineLoginRequestDto,
    signal,
  });
};

export const getPostApiAuthLineCallbackMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthLineCallback>>,
    TError,
    { data: LineLoginRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthLineCallback>>,
  TError,
  { data: LineLoginRequestDto },
  TContext
> => {
  const mutationKey = ["postApiAuthLineCallback"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthLineCallback>>,
    { data: LineLoginRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthLineCallback(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthLineCallbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthLineCallback>>
>;
export type PostApiAuthLineCallbackMutationBody = LineLoginRequestDto;
export type PostApiAuthLineCallbackMutationError = ApiResponse;

/**
 * @summary LINE 登入回呼
 */
export const usePostApiAuthLineCallback = <
  TError = ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLineCallback>>,
      TError,
      { data: LineLoginRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthLineCallback>>,
  TError,
  { data: LineLoginRequestDto },
  TContext
> => {
  const mutationOptions = getPostApiAuthLineCallbackMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 取得 Google 登入 URL
 */
export const getApiAuthGoogleUrl = (
  params?: GetApiAuthGoogleUrlParams,
  signal?: AbortSignal,
) => {
  return axiosInstance<ObjectApiResponse>({
    url: `/api/Auth/google/url`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiAuthGoogleUrlQueryKey = (
  params?: GetApiAuthGoogleUrlParams,
) => {
  return [`/api/Auth/google/url`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuthGoogleUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
  TError = ApiResponse,
>(
  params?: GetApiAuthGoogleUrlParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiAuthGoogleUrlQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAuthGoogleUrl>>
  > = ({ signal }) => getApiAuthGoogleUrl(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthGoogleUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAuthGoogleUrl>>
>;
export type GetApiAuthGoogleUrlQueryError = ApiResponse;

export function useGetApiAuthGoogleUrl<
  TData = Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
  TError = ApiResponse,
>(
  params: undefined | GetApiAuthGoogleUrlParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogleUrl>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthGoogleUrl<
  TData = Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
  TError = ApiResponse,
>(
  params?: GetApiAuthGoogleUrlParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogleUrl>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthGoogleUrl<
  TData = Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
  TError = ApiResponse,
>(
  params?: GetApiAuthGoogleUrlParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 取得 Google 登入 URL
 */

export function useGetApiAuthGoogleUrl<
  TData = Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
  TError = ApiResponse,
>(
  params?: GetApiAuthGoogleUrlParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthGoogleUrl>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAuthGoogleUrlQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Google 登入回呼
 */
export const postApiAuthGoogleCallback = (
  googleLoginRequestDto: GoogleLoginRequestDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<AuthResultDtoApiResponse>({
    url: `/api/Auth/google/callback`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: googleLoginRequestDto,
    signal,
  });
};

export const getPostApiAuthGoogleCallbackMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthGoogleCallback>>,
    TError,
    { data: GoogleLoginRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthGoogleCallback>>,
  TError,
  { data: GoogleLoginRequestDto },
  TContext
> => {
  const mutationKey = ["postApiAuthGoogleCallback"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthGoogleCallback>>,
    { data: GoogleLoginRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthGoogleCallback(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthGoogleCallbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthGoogleCallback>>
>;
export type PostApiAuthGoogleCallbackMutationBody = GoogleLoginRequestDto;
export type PostApiAuthGoogleCallbackMutationError = ApiResponse;

/**
 * @summary Google 登入回呼
 */
export const usePostApiAuthGoogleCallback = <
  TError = ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthGoogleCallback>>,
      TError,
      { data: GoogleLoginRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthGoogleCallback>>,
  TError,
  { data: GoogleLoginRequestDto },
  TContext
> => {
  const mutationOptions = getPostApiAuthGoogleCallbackMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 刷新 Token
 */
export const postApiAuthRefresh = (
  refreshTokenRequestDto: RefreshTokenRequestDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<AuthResultDtoApiResponse>({
    url: `/api/Auth/refresh`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: refreshTokenRequestDto,
    signal,
  });
};

export const getPostApiAuthRefreshMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthRefresh>>,
    TError,
    { data: RefreshTokenRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthRefresh>>,
  TError,
  { data: RefreshTokenRequestDto },
  TContext
> => {
  const mutationKey = ["postApiAuthRefresh"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthRefresh>>,
    { data: RefreshTokenRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthRefresh(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthRefresh>>
>;
export type PostApiAuthRefreshMutationBody = RefreshTokenRequestDto;
export type PostApiAuthRefreshMutationError = ApiResponse;

/**
 * @summary 刷新 Token
 */
export const usePostApiAuthRefresh = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthRefresh>>,
      TError,
      { data: RefreshTokenRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthRefresh>>,
  TError,
  { data: RefreshTokenRequestDto },
  TContext
> => {
  const mutationOptions = getPostApiAuthRefreshMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 登出
 */
export const postApiAuthLogout = (
  refreshTokenRequestDto: RefreshTokenRequestDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponse>({
    url: `/api/Auth/logout`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: refreshTokenRequestDto,
    signal,
  });
};

export const getPostApiAuthLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthLogout>>,
    TError,
    { data: RefreshTokenRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthLogout>>,
  TError,
  { data: RefreshTokenRequestDto },
  TContext
> => {
  const mutationKey = ["postApiAuthLogout"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthLogout>>,
    { data: RefreshTokenRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthLogout(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthLogout>>
>;
export type PostApiAuthLogoutMutationBody = RefreshTokenRequestDto;
export type PostApiAuthLogoutMutationError = unknown;

/**
 * @summary 登出
 */
export const usePostApiAuthLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLogout>>,
      TError,
      { data: RefreshTokenRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthLogout>>,
  TError,
  { data: RefreshTokenRequestDto },
  TContext
> => {
  const mutationOptions = getPostApiAuthLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 取得目前使用者資訊
 */
export const getApiAuthMe = (signal?: AbortSignal) => {
  return axiosInstance<UserDtoApiResponse>({
    url: `/api/Auth/me`,
    method: "GET",
    signal,
  });
};

export const getGetApiAuthMeQueryKey = () => {
  return [`/api/Auth/me`] as const;
};

export const getGetApiAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ApiResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthMe>>> = ({
    signal,
  }) => getApiAuthMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAuthMe>>
>;
export type GetApiAuthMeQueryError = ApiResponse;

export function useGetApiAuthMe<
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ApiResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthMe<
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ApiResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthMe<
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ApiResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 取得目前使用者資訊
 */

export function useGetApiAuthMe<
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ApiResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAuthMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
