/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiResponse,
  CreateExpenseDto,
  ExpenseDtoApiResponse,
  UpdateExpenseDto,
} from "../../models";

import { customInstance } from "../../../shared/lib/axios-instance";

/**
 * @summary 根據 ID 取得費用
 */
export const getApiSnapSplitExpensesId = (id: string, signal?: AbortSignal) => {
  return customInstance<ExpenseDtoApiResponse>({
    url: `/api/snap-split/expenses/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiSnapSplitExpensesIdQueryKey = (id?: string) => {
  return [`/api/snap-split/expenses/${id}`] as const;
};

export const getGetApiSnapSplitExpensesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiSnapSplitExpensesIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>
  > = ({ signal }) => getApiSnapSplitExpensesId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetApiSnapSplitExpensesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>
>;
export type GetApiSnapSplitExpensesIdQueryError = ApiResponse;

export function useGetApiSnapSplitExpensesId<
  TData = Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
  TError = ApiResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
          TError,
          Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetApiSnapSplitExpensesId<
  TData = Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
          TError,
          Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetApiSnapSplitExpensesId<
  TData = Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary 根據 ID 取得費用
 */

export function useGetApiSnapSplitExpensesId<
  TData = Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSnapSplitExpensesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetApiSnapSplitExpensesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 更新費用
 */
export const putApiSnapSplitExpensesId = (
  id: string,
  updateExpenseDto: UpdateExpenseDto,
) => {
  return customInstance<ExpenseDtoApiResponse>({
    url: `/api/snap-split/expenses/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateExpenseDto,
  });
};

export const getPutApiSnapSplitExpensesIdMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiSnapSplitExpensesId>>,
    TError,
    { id: string; data: UpdateExpenseDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiSnapSplitExpensesId>>,
  TError,
  { id: string; data: UpdateExpenseDto },
  TContext
> => {
  const mutationKey = ["putApiSnapSplitExpensesId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiSnapSplitExpensesId>>,
    { id: string; data: UpdateExpenseDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiSnapSplitExpensesId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiSnapSplitExpensesIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiSnapSplitExpensesId>>
>;
export type PutApiSnapSplitExpensesIdMutationBody = UpdateExpenseDto;
export type PutApiSnapSplitExpensesIdMutationError = ApiResponse | ApiResponse;

/**
 * @summary 更新費用
 */
export const usePutApiSnapSplitExpensesId = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiSnapSplitExpensesId>>,
      TError,
      { id: string; data: UpdateExpenseDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiSnapSplitExpensesId>>,
  TError,
  { id: string; data: UpdateExpenseDto },
  TContext
> => {
  const mutationOptions = getPutApiSnapSplitExpensesIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 刪除費用
 */
export const deleteApiSnapSplitExpensesId = (id: string) => {
  return customInstance<void>({
    url: `/api/snap-split/expenses/${id}`,
    method: "DELETE",
  });
};

export const getDeleteApiSnapSplitExpensesIdMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiSnapSplitExpensesId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiSnapSplitExpensesId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiSnapSplitExpensesId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiSnapSplitExpensesId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiSnapSplitExpensesId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiSnapSplitExpensesIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiSnapSplitExpensesId>>
>;

export type DeleteApiSnapSplitExpensesIdMutationError = ApiResponse;

/**
 * @summary 刪除費用
 */
export const useDeleteApiSnapSplitExpensesId = <
  TError = ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiSnapSplitExpensesId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiSnapSplitExpensesId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getDeleteApiSnapSplitExpensesIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 新增費用到帳單
 */
export const postApiSnapSplitBillsBillIdExpenses = (
  billId: string,
  createExpenseDto: CreateExpenseDto,
  signal?: AbortSignal,
) => {
  return customInstance<ExpenseDtoApiResponse>({
    url: `/api/snap-split/bills/${billId}/expenses`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createExpenseDto,
    signal,
  });
};

export const getPostApiSnapSplitBillsBillIdExpensesMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdExpenses>>,
    TError,
    { billId: string; data: CreateExpenseDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdExpenses>>,
  TError,
  { billId: string; data: CreateExpenseDto },
  TContext
> => {
  const mutationKey = ["postApiSnapSplitBillsBillIdExpenses"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdExpenses>>,
    { billId: string; data: CreateExpenseDto }
  > = (props) => {
    const { billId, data } = props ?? {};

    return postApiSnapSplitBillsBillIdExpenses(billId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiSnapSplitBillsBillIdExpensesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdExpenses>>
>;
export type PostApiSnapSplitBillsBillIdExpensesMutationBody = CreateExpenseDto;
export type PostApiSnapSplitBillsBillIdExpensesMutationError =
  | ApiResponse
  | ApiResponse;

/**
 * @summary 新增費用到帳單
 */
export const usePostApiSnapSplitBillsBillIdExpenses = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdExpenses>>,
      TError,
      { billId: string; data: CreateExpenseDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdExpenses>>,
  TError,
  { billId: string; data: CreateExpenseDto },
  TContext
> => {
  const mutationOptions =
    getPostApiSnapSplitBillsBillIdExpensesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
