/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiResponse,
  SettlementResultDtoApiResponse,
  ToggleSettledRequest,
} from "../../models";

import { axiosInstance } from "../../axios-instance";

/**
 * @summary 計算帳單結算
 */
export const getApiBillsBillIdSettlement = (
  billId: string,
  signal?: AbortSignal,
) => {
  return axiosInstance<SettlementResultDtoApiResponse>({
    url: `/api/bills/${billId}/settlement`,
    method: "GET",
    signal,
  });
};

export const getGetApiBillsBillIdSettlementQueryKey = (billId?: string) => {
  return [`/api/bills/${billId}/settlement`] as const;
};

export const getGetApiBillsBillIdSettlementQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
  TError = ApiResponse,
>(
  billId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiBillsBillIdSettlementQueryKey(billId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>
  > = ({ signal }) => getApiBillsBillIdSettlement(billId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!billId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiBillsBillIdSettlementQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>
>;
export type GetApiBillsBillIdSettlementQueryError = ApiResponse;

export function useGetApiBillsBillIdSettlement<
  TData = Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
  TError = ApiResponse,
>(
  billId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
          TError,
          Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBillsBillIdSettlement<
  TData = Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
  TError = ApiResponse,
>(
  billId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
          TError,
          Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBillsBillIdSettlement<
  TData = Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
  TError = ApiResponse,
>(
  billId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 計算帳單結算
 */

export function useGetApiBillsBillIdSettlement<
  TData = Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
  TError = ApiResponse,
>(
  billId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBillsBillIdSettlement>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiBillsBillIdSettlementQueryOptions(
    billId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 切換轉帳結清狀態
 */
export const postApiBillsBillIdSettlementToggle = (
  billId: string,
  toggleSettledRequest: ToggleSettledRequest,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/api/bills/${billId}/settlement/toggle`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: toggleSettledRequest,
    signal,
  });
};

export const getPostApiBillsBillIdSettlementToggleMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiBillsBillIdSettlementToggle>>,
    TError,
    { billId: string; data: ToggleSettledRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiBillsBillIdSettlementToggle>>,
  TError,
  { billId: string; data: ToggleSettledRequest },
  TContext
> => {
  const mutationKey = ["postApiBillsBillIdSettlementToggle"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiBillsBillIdSettlementToggle>>,
    { billId: string; data: ToggleSettledRequest }
  > = (props) => {
    const { billId, data } = props ?? {};

    return postApiBillsBillIdSettlementToggle(billId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiBillsBillIdSettlementToggleMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiBillsBillIdSettlementToggle>>
>;
export type PostApiBillsBillIdSettlementToggleMutationBody =
  ToggleSettledRequest;
export type PostApiBillsBillIdSettlementToggleMutationError = ApiResponse;

/**
 * @summary 切換轉帳結清狀態
 */
export const usePostApiBillsBillIdSettlementToggle = <
  TError = ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiBillsBillIdSettlementToggle>>,
      TError,
      { billId: string; data: ToggleSettledRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiBillsBillIdSettlementToggle>>,
  TError,
  { billId: string; data: ToggleSettledRequest },
  TContext
> => {
  const mutationOptions =
    getPostApiBillsBillIdSettlementToggleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
