/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiResponse,
  CreateExpenseDto,
  ExpenseDtoApiResponse,
  UpdateExpenseDto,
} from "../../models";

import { axiosInstance } from "../../axios-instance";

/**
 * @summary 根據 ID 取得費用
 */
export const getApiExpensesId = (id: string, signal?: AbortSignal) => {
  return axiosInstance<ExpenseDtoApiResponse>({
    url: `/api/expenses/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiExpensesIdQueryKey = (id?: string) => {
  return [`/api/expenses/${id}`] as const;
};

export const getGetApiExpensesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiExpensesId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExpensesId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiExpensesIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiExpensesId>>
  > = ({ signal }) => getApiExpensesId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiExpensesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiExpensesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiExpensesId>>
>;
export type GetApiExpensesIdQueryError = ApiResponse;

export function useGetApiExpensesId<
  TData = Awaited<ReturnType<typeof getApiExpensesId>>,
  TError = ApiResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExpensesId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExpensesId>>,
          TError,
          Awaited<ReturnType<typeof getApiExpensesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExpensesId<
  TData = Awaited<ReturnType<typeof getApiExpensesId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExpensesId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExpensesId>>,
          TError,
          Awaited<ReturnType<typeof getApiExpensesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExpensesId<
  TData = Awaited<ReturnType<typeof getApiExpensesId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExpensesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 根據 ID 取得費用
 */

export function useGetApiExpensesId<
  TData = Awaited<ReturnType<typeof getApiExpensesId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExpensesId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiExpensesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 更新費用
 */
export const putApiExpensesId = (
  id: string,
  updateExpenseDto: UpdateExpenseDto,
) => {
  return axiosInstance<ExpenseDtoApiResponse>({
    url: `/api/expenses/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateExpenseDto,
  });
};

export const getPutApiExpensesIdMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiExpensesId>>,
    TError,
    { id: string; data: UpdateExpenseDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiExpensesId>>,
  TError,
  { id: string; data: UpdateExpenseDto },
  TContext
> => {
  const mutationKey = ["putApiExpensesId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiExpensesId>>,
    { id: string; data: UpdateExpenseDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiExpensesId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiExpensesIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiExpensesId>>
>;
export type PutApiExpensesIdMutationBody = UpdateExpenseDto;
export type PutApiExpensesIdMutationError = ApiResponse | ApiResponse;

/**
 * @summary 更新費用
 */
export const usePutApiExpensesId = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiExpensesId>>,
      TError,
      { id: string; data: UpdateExpenseDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiExpensesId>>,
  TError,
  { id: string; data: UpdateExpenseDto },
  TContext
> => {
  const mutationOptions = getPutApiExpensesIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 刪除費用
 */
export const deleteApiExpensesId = (id: string) => {
  return axiosInstance<void>({ url: `/api/expenses/${id}`, method: "DELETE" });
};

export const getDeleteApiExpensesIdMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiExpensesId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiExpensesId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiExpensesId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiExpensesId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiExpensesId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiExpensesIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiExpensesId>>
>;

export type DeleteApiExpensesIdMutationError = ApiResponse;

/**
 * @summary 刪除費用
 */
export const useDeleteApiExpensesId = <
  TError = ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiExpensesId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiExpensesId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiExpensesIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 新增費用到帳單
 */
export const postApiBillsBillIdExpenses = (
  billId: string,
  createExpenseDto: CreateExpenseDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<ExpenseDtoApiResponse>({
    url: `/api/bills/${billId}/expenses`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createExpenseDto,
    signal,
  });
};

export const getPostApiBillsBillIdExpensesMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiBillsBillIdExpenses>>,
    TError,
    { billId: string; data: CreateExpenseDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiBillsBillIdExpenses>>,
  TError,
  { billId: string; data: CreateExpenseDto },
  TContext
> => {
  const mutationKey = ["postApiBillsBillIdExpenses"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiBillsBillIdExpenses>>,
    { billId: string; data: CreateExpenseDto }
  > = (props) => {
    const { billId, data } = props ?? {};

    return postApiBillsBillIdExpenses(billId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiBillsBillIdExpensesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiBillsBillIdExpenses>>
>;
export type PostApiBillsBillIdExpensesMutationBody = CreateExpenseDto;
export type PostApiBillsBillIdExpensesMutationError = ApiResponse | ApiResponse;

/**
 * @summary 新增費用到帳單
 */
export const usePostApiBillsBillIdExpenses = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiBillsBillIdExpenses>>,
      TError,
      { billId: string; data: CreateExpenseDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiBillsBillIdExpenses>>,
  TError,
  { billId: string; data: CreateExpenseDto },
  TContext
> => {
  const mutationOptions = getPostApiBillsBillIdExpensesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
