/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiResponse,
  BillDtoApiResponse,
  CreateBillDto,
  ObjectApiResponse,
  SyncBillRequestDto,
  SyncBillResponseDtoApiResponse,
  UpdateBillDto,
} from "../../models";

import { axiosInstance } from "../../axios-instance";

/**
 * @summary 根據 ID 取得帳單
 */
export const getApiBillsId = (id: string, signal?: AbortSignal) => {
  return axiosInstance<BillDtoApiResponse>({
    url: `/api/Bills/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiBillsIdQueryKey = (id?: string) => {
  return [`/api/Bills/${id}`] as const;
};

export const getGetApiBillsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiBillsId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiBillsId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiBillsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBillsId>>> = ({
    signal,
  }) => getApiBillsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiBillsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiBillsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiBillsId>>
>;
export type GetApiBillsIdQueryError = ApiResponse;

export function useGetApiBillsId<
  TData = Awaited<ReturnType<typeof getApiBillsId>>,
  TError = ApiResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiBillsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBillsId>>,
          TError,
          Awaited<ReturnType<typeof getApiBillsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBillsId<
  TData = Awaited<ReturnType<typeof getApiBillsId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiBillsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBillsId>>,
          TError,
          Awaited<ReturnType<typeof getApiBillsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBillsId<
  TData = Awaited<ReturnType<typeof getApiBillsId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiBillsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 根據 ID 取得帳單
 */

export function useGetApiBillsId<
  TData = Awaited<ReturnType<typeof getApiBillsId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiBillsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiBillsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 更新帳單
 */
export const putApiBillsId = (id: string, updateBillDto: UpdateBillDto) => {
  return axiosInstance<BillDtoApiResponse>({
    url: `/api/Bills/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateBillDto,
  });
};

export const getPutApiBillsIdMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiBillsId>>,
    TError,
    { id: string; data: UpdateBillDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiBillsId>>,
  TError,
  { id: string; data: UpdateBillDto },
  TContext
> => {
  const mutationKey = ["putApiBillsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiBillsId>>,
    { id: string; data: UpdateBillDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiBillsId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiBillsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiBillsId>>
>;
export type PutApiBillsIdMutationBody = UpdateBillDto;
export type PutApiBillsIdMutationError = ApiResponse;

/**
 * @summary 更新帳單
 */
export const usePutApiBillsId = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiBillsId>>,
      TError,
      { id: string; data: UpdateBillDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiBillsId>>,
  TError,
  { id: string; data: UpdateBillDto },
  TContext
> => {
  const mutationOptions = getPutApiBillsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 刪除帳單
 */
export const deleteApiBillsId = (id: string) => {
  return axiosInstance<void>({ url: `/api/Bills/${id}`, method: "DELETE" });
};

export const getDeleteApiBillsIdMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiBillsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiBillsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiBillsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiBillsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiBillsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiBillsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiBillsId>>
>;

export type DeleteApiBillsIdMutationError = ApiResponse;

/**
 * @summary 刪除帳單
 */
export const useDeleteApiBillsId = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiBillsId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiBillsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiBillsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 根據分享碼取得帳單
 */
export const getApiBillsShareShareCode = (
  shareCode: string,
  signal?: AbortSignal,
) => {
  return axiosInstance<BillDtoApiResponse>({
    url: `/api/Bills/share/${shareCode}`,
    method: "GET",
    signal,
  });
};

export const getGetApiBillsShareShareCodeQueryKey = (shareCode?: string) => {
  return [`/api/Bills/share/${shareCode}`] as const;
};

export const getGetApiBillsShareShareCodeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
  TError = ApiResponse,
>(
  shareCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiBillsShareShareCodeQueryKey(shareCode);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiBillsShareShareCode>>
  > = ({ signal }) => getApiBillsShareShareCode(shareCode, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!shareCode,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiBillsShareShareCodeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiBillsShareShareCode>>
>;
export type GetApiBillsShareShareCodeQueryError = ApiResponse;

export function useGetApiBillsShareShareCode<
  TData = Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
  TError = ApiResponse,
>(
  shareCode: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
          TError,
          Awaited<ReturnType<typeof getApiBillsShareShareCode>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBillsShareShareCode<
  TData = Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
  TError = ApiResponse,
>(
  shareCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
          TError,
          Awaited<ReturnType<typeof getApiBillsShareShareCode>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBillsShareShareCode<
  TData = Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
  TError = ApiResponse,
>(
  shareCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 根據分享碼取得帳單
 */

export function useGetApiBillsShareShareCode<
  TData = Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
  TError = ApiResponse,
>(
  shareCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBillsShareShareCode>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiBillsShareShareCodeQueryOptions(
    shareCode,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 建立新帳單
 */
export const postApiBills = (
  createBillDto: CreateBillDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<BillDtoApiResponse>({
    url: `/api/Bills`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createBillDto,
    signal,
  });
};

export const getPostApiBillsMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiBills>>,
    TError,
    { data: CreateBillDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiBills>>,
  TError,
  { data: CreateBillDto },
  TContext
> => {
  const mutationKey = ["postApiBills"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiBills>>,
    { data: CreateBillDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiBills(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiBillsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiBills>>
>;
export type PostApiBillsMutationBody = CreateBillDto;
export type PostApiBillsMutationError = ApiResponse;

/**
 * @summary 建立新帳單
 */
export const usePostApiBills = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiBills>>,
      TError,
      { data: CreateBillDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiBills>>,
  TError,
  { data: CreateBillDto },
  TContext
> => {
  const mutationOptions = getPostApiBillsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 產生分享碼
 */
export const postApiBillsIdShareCode = (id: string, signal?: AbortSignal) => {
  return axiosInstance<ObjectApiResponse>({
    url: `/api/Bills/${id}/share-code`,
    method: "POST",
    signal,
  });
};

export const getPostApiBillsIdShareCodeMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiBillsIdShareCode>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiBillsIdShareCode>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["postApiBillsIdShareCode"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiBillsIdShareCode>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postApiBillsIdShareCode(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiBillsIdShareCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiBillsIdShareCode>>
>;

export type PostApiBillsIdShareCodeMutationError = ApiResponse;

/**
 * @summary 產生分享碼
 */
export const usePostApiBillsIdShareCode = <
  TError = ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiBillsIdShareCode>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiBillsIdShareCode>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getPostApiBillsIdShareCodeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 同步帳單（含成員、費用完整同步）
 */
export const postApiBillsSync = (
  syncBillRequestDto: SyncBillRequestDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<SyncBillResponseDtoApiResponse>({
    url: `/api/Bills/sync`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: syncBillRequestDto,
    signal,
  });
};

export const getPostApiBillsSyncMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiBillsSync>>,
    TError,
    { data: SyncBillRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiBillsSync>>,
  TError,
  { data: SyncBillRequestDto },
  TContext
> => {
  const mutationKey = ["postApiBillsSync"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiBillsSync>>,
    { data: SyncBillRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiBillsSync(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiBillsSyncMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiBillsSync>>
>;
export type PostApiBillsSyncMutationBody = SyncBillRequestDto;
export type PostApiBillsSyncMutationError = ApiResponse | ApiResponse;

/**
 * @summary 同步帳單（含成員、費用完整同步）
 */
export const usePostApiBillsSync = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiBillsSync>>,
      TError,
      { data: SyncBillRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiBillsSync>>,
  TError,
  { data: SyncBillRequestDto },
  TContext
> => {
  const mutationOptions = getPostApiBillsSyncMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
