/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiResponse,
  BillDtoApiResponse,
  BillDtoIReadOnlyListApiResponse,
  CreateBillDto,
  DeltaSyncRequest,
  DeltaSyncResponseApiResponse,
  ObjectApiResponse,
  SyncBillRequestDto,
  SyncBillResponseDtoApiResponse,
  UpdateBillDto,
} from "../../models";

import { axiosInstance } from "../../axios-instance";

/**
 * @summary 根據 ID 取得帳單
 */
export const getBillById = (id: string, signal?: AbortSignal) => {
  return axiosInstance<BillDtoApiResponse>({
    url: `/api/Bills/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetBillByIdQueryKey = (id?: string) => {
  return [`/api/Bills/${id}`] as const;
};

export const getGetBillByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getBillById>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBillById>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBillByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBillById>>> = ({
    signal,
  }) => getBillById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBillById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBillByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBillById>>
>;
export type GetBillByIdQueryError = ApiResponse;

export function useGetBillById<
  TData = Awaited<ReturnType<typeof getBillById>>,
  TError = ApiResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBillById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBillById>>,
          TError,
          Awaited<ReturnType<typeof getBillById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBillById<
  TData = Awaited<ReturnType<typeof getBillById>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBillById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBillById>>,
          TError,
          Awaited<ReturnType<typeof getBillById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBillById<
  TData = Awaited<ReturnType<typeof getBillById>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBillById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 根據 ID 取得帳單
 */

export function useGetBillById<
  TData = Awaited<ReturnType<typeof getBillById>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBillById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBillByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 更新帳單
 */
export const updateBill = (id: string, updateBillDto: UpdateBillDto) => {
  return axiosInstance<BillDtoApiResponse>({
    url: `/api/Bills/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateBillDto,
  });
};

export const getUpdateBillMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBill>>,
    TError,
    { id: string; data: UpdateBillDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateBill>>,
  TError,
  { id: string; data: UpdateBillDto },
  TContext
> => {
  const mutationKey = ["updateBill"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateBill>>,
    { id: string; data: UpdateBillDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateBill(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateBillMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateBill>>
>;
export type UpdateBillMutationBody = UpdateBillDto;
export type UpdateBillMutationError = ApiResponse;

/**
 * @summary 更新帳單
 */
export const useUpdateBill = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateBill>>,
      TError,
      { id: string; data: UpdateBillDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateBill>>,
  TError,
  { id: string; data: UpdateBillDto },
  TContext
> => {
  const mutationOptions = getUpdateBillMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 刪除帳單
 */
export const deleteBill = (id: string) => {
  return axiosInstance<void>({ url: `/api/Bills/${id}`, method: "DELETE" });
};

export const getDeleteBillMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBill>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteBill>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteBill"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteBill>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteBill(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteBillMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteBill>>
>;

export type DeleteBillMutationError = ApiResponse;

/**
 * @summary 刪除帳單
 */
export const useDeleteBill = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteBill>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteBill>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteBillMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 根據分享碼取得帳單
 */
export const getBillByShareCode = (shareCode: string, signal?: AbortSignal) => {
  return axiosInstance<BillDtoApiResponse>({
    url: `/api/Bills/share/${shareCode}`,
    method: "GET",
    signal,
  });
};

export const getGetBillByShareCodeQueryKey = (shareCode?: string) => {
  return [`/api/Bills/share/${shareCode}`] as const;
};

export const getGetBillByShareCodeQueryOptions = <
  TData = Awaited<ReturnType<typeof getBillByShareCode>>,
  TError = ApiResponse,
>(
  shareCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillByShareCode>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBillByShareCodeQueryKey(shareCode);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBillByShareCode>>
  > = ({ signal }) => getBillByShareCode(shareCode, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!shareCode,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBillByShareCode>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBillByShareCodeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBillByShareCode>>
>;
export type GetBillByShareCodeQueryError = ApiResponse;

export function useGetBillByShareCode<
  TData = Awaited<ReturnType<typeof getBillByShareCode>>,
  TError = ApiResponse,
>(
  shareCode: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillByShareCode>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBillByShareCode>>,
          TError,
          Awaited<ReturnType<typeof getBillByShareCode>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBillByShareCode<
  TData = Awaited<ReturnType<typeof getBillByShareCode>>,
  TError = ApiResponse,
>(
  shareCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillByShareCode>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBillByShareCode>>,
          TError,
          Awaited<ReturnType<typeof getBillByShareCode>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBillByShareCode<
  TData = Awaited<ReturnType<typeof getBillByShareCode>>,
  TError = ApiResponse,
>(
  shareCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillByShareCode>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 根據分享碼取得帳單
 */

export function useGetBillByShareCode<
  TData = Awaited<ReturnType<typeof getBillByShareCode>>,
  TError = ApiResponse,
>(
  shareCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillByShareCode>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBillByShareCodeQueryOptions(shareCode, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 取得當前使用者參與的帳單
 */
export const getMyBills = (signal?: AbortSignal) => {
  return axiosInstance<BillDtoIReadOnlyListApiResponse>({
    url: `/api/Bills/mine`,
    method: "GET",
    signal,
  });
};

export const getGetMyBillsQueryKey = () => {
  return [`/api/Bills/mine`] as const;
};

export const getGetMyBillsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyBills>>,
  TError = ApiResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMyBills>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyBillsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyBills>>> = ({
    signal,
  }) => getMyBills(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyBills>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyBillsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyBills>>
>;
export type GetMyBillsQueryError = ApiResponse;

export function useGetMyBills<
  TData = Awaited<ReturnType<typeof getMyBills>>,
  TError = ApiResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyBills>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBills>>,
          TError,
          Awaited<ReturnType<typeof getMyBills>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyBills<
  TData = Awaited<ReturnType<typeof getMyBills>>,
  TError = ApiResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyBills>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBills>>,
          TError,
          Awaited<ReturnType<typeof getMyBills>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyBills<
  TData = Awaited<ReturnType<typeof getMyBills>>,
  TError = ApiResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyBills>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 取得當前使用者參與的帳單
 */

export function useGetMyBills<
  TData = Awaited<ReturnType<typeof getMyBills>>,
  TError = ApiResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyBills>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyBillsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 建立新帳單
 */
export const createBill = (
  createBillDto: CreateBillDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<BillDtoApiResponse>({
    url: `/api/Bills`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createBillDto,
    signal,
  });
};

export const getCreateBillMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBill>>,
    TError,
    { data: CreateBillDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createBill>>,
  TError,
  { data: CreateBillDto },
  TContext
> => {
  const mutationKey = ["createBill"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createBill>>,
    { data: CreateBillDto }
  > = (props) => {
    const { data } = props ?? {};

    return createBill(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateBillMutationResult = NonNullable<
  Awaited<ReturnType<typeof createBill>>
>;
export type CreateBillMutationBody = CreateBillDto;
export type CreateBillMutationError = ApiResponse;

/**
 * @summary 建立新帳單
 */
export const useCreateBill = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createBill>>,
      TError,
      { data: CreateBillDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createBill>>,
  TError,
  { data: CreateBillDto },
  TContext
> => {
  const mutationOptions = getCreateBillMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 產生分享碼
 */
export const generateShareCode = (id: string, signal?: AbortSignal) => {
  return axiosInstance<ObjectApiResponse>({
    url: `/api/Bills/${id}/share-code`,
    method: "POST",
    signal,
  });
};

export const getGenerateShareCodeMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateShareCode>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateShareCode>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["generateShareCode"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateShareCode>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return generateShareCode(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateShareCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateShareCode>>
>;

export type GenerateShareCodeMutationError = ApiResponse;

/**
 * @summary 產生分享碼
 */
export const useGenerateShareCode = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generateShareCode>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof generateShareCode>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getGenerateShareCodeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 同步帳單資料（增量更新）
 */
export const syncBill = (
  syncBillRequestDto: SyncBillRequestDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<SyncBillResponseDtoApiResponse>({
    url: `/api/Bills/sync`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: syncBillRequestDto,
    signal,
  });
};

export const getSyncBillMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof syncBill>>,
    TError,
    { data: SyncBillRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof syncBill>>,
  TError,
  { data: SyncBillRequestDto },
  TContext
> => {
  const mutationKey = ["syncBill"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof syncBill>>,
    { data: SyncBillRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return syncBill(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SyncBillMutationResult = NonNullable<
  Awaited<ReturnType<typeof syncBill>>
>;
export type SyncBillMutationBody = SyncBillRequestDto;
export type SyncBillMutationError = ApiResponse | ApiResponse;

/**
 * @summary 同步帳單資料（增量更新）
 */
export const useSyncBill = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof syncBill>>,
      TError,
      { data: SyncBillRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof syncBill>>,
  TError,
  { data: SyncBillRequestDto },
  TContext
> => {
  const mutationOptions = getSyncBillMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delta 同步帳單資料（v3.2 新機制）
 */
export const deltaSyncBill = (
  id: string,
  deltaSyncRequest: DeltaSyncRequest,
  signal?: AbortSignal,
) => {
  return axiosInstance<DeltaSyncResponseApiResponse>({
    url: `/api/Bills/${id}/delta-sync`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: deltaSyncRequest,
    signal,
  });
};

export const getDeltaSyncBillMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deltaSyncBill>>,
    TError,
    { id: string; data: DeltaSyncRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deltaSyncBill>>,
  TError,
  { id: string; data: DeltaSyncRequest },
  TContext
> => {
  const mutationKey = ["deltaSyncBill"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deltaSyncBill>>,
    { id: string; data: DeltaSyncRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return deltaSyncBill(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeltaSyncBillMutationResult = NonNullable<
  Awaited<ReturnType<typeof deltaSyncBill>>
>;
export type DeltaSyncBillMutationBody = DeltaSyncRequest;
export type DeltaSyncBillMutationError = ApiResponse | ApiResponse;

/**
 * @summary Delta 同步帳單資料（v3.2 新機制）
 */
export const useDeltaSyncBill = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deltaSyncBill>>,
      TError,
      { id: string; data: DeltaSyncRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deltaSyncBill>>,
  TError,
  { id: string; data: DeltaSyncRequest },
  TContext
> => {
  const mutationOptions = getDeltaSyncBillMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
