/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  ApiResponse,
  ClaimMemberDto,
  ClaimMemberResultDtoApiResponse,
  CreateMemberDto,
  MemberDtoApiResponse,
  UpdateMemberDto,
} from "../../models";

import { axiosInstance } from "../../axios-instance";

/**
 * @summary 新增成員到帳單
 */
export const postApiBillsBillIdMembers = (
  billId: string,
  createMemberDto: CreateMemberDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<MemberDtoApiResponse>({
    url: `/api/bills/${billId}/members`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createMemberDto,
    signal,
  });
};

export const getPostApiBillsBillIdMembersMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiBillsBillIdMembers>>,
    TError,
    { billId: string; data: CreateMemberDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiBillsBillIdMembers>>,
  TError,
  { billId: string; data: CreateMemberDto },
  TContext
> => {
  const mutationKey = ["postApiBillsBillIdMembers"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiBillsBillIdMembers>>,
    { billId: string; data: CreateMemberDto }
  > = (props) => {
    const { billId, data } = props ?? {};

    return postApiBillsBillIdMembers(billId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiBillsBillIdMembersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiBillsBillIdMembers>>
>;
export type PostApiBillsBillIdMembersMutationBody = CreateMemberDto;
export type PostApiBillsBillIdMembersMutationError = ApiResponse | ApiResponse;

/**
 * @summary 新增成員到帳單
 */
export const usePostApiBillsBillIdMembers = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiBillsBillIdMembers>>,
      TError,
      { billId: string; data: CreateMemberDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiBillsBillIdMembers>>,
  TError,
  { billId: string; data: CreateMemberDto },
  TContext
> => {
  const mutationOptions = getPostApiBillsBillIdMembersMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 更新成員
 */
export const putApiMembersId = (
  id: string,
  updateMemberDto: UpdateMemberDto,
) => {
  return axiosInstance<MemberDtoApiResponse>({
    url: `/api/members/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateMemberDto,
  });
};

export const getPutApiMembersIdMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiMembersId>>,
    TError,
    { id: string; data: UpdateMemberDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiMembersId>>,
  TError,
  { id: string; data: UpdateMemberDto },
  TContext
> => {
  const mutationKey = ["putApiMembersId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiMembersId>>,
    { id: string; data: UpdateMemberDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiMembersId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiMembersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiMembersId>>
>;
export type PutApiMembersIdMutationBody = UpdateMemberDto;
export type PutApiMembersIdMutationError = ApiResponse;

/**
 * @summary 更新成員
 */
export const usePutApiMembersId = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiMembersId>>,
      TError,
      { id: string; data: UpdateMemberDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiMembersId>>,
  TError,
  { id: string; data: UpdateMemberDto },
  TContext
> => {
  const mutationOptions = getPutApiMembersIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 刪除成員
 */
export const deleteApiMembersId = (id: string) => {
  return axiosInstance<void>({ url: `/api/members/${id}`, method: "DELETE" });
};

export const getDeleteApiMembersIdMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiMembersId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiMembersId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiMembersId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiMembersId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiMembersId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiMembersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiMembersId>>
>;

export type DeleteApiMembersIdMutationError = ApiResponse | ApiResponse;

/**
 * @summary 刪除成員
 */
export const useDeleteApiMembersId = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiMembersId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiMembersId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiMembersIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 認領成員（綁定當前使用者）
 */
export const postApiMembersIdClaim = (
  id: string,
  claimMemberDto: ClaimMemberDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<ClaimMemberResultDtoApiResponse>({
    url: `/api/members/${id}/claim`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: claimMemberDto,
    signal,
  });
};

export const getPostApiMembersIdClaimMutationOptions = <
  TError = ApiResponse | ApiResponse | ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiMembersIdClaim>>,
    TError,
    { id: string; data: ClaimMemberDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiMembersIdClaim>>,
  TError,
  { id: string; data: ClaimMemberDto },
  TContext
> => {
  const mutationKey = ["postApiMembersIdClaim"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiMembersIdClaim>>,
    { id: string; data: ClaimMemberDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return postApiMembersIdClaim(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiMembersIdClaimMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiMembersIdClaim>>
>;
export type PostApiMembersIdClaimMutationBody = ClaimMemberDto;
export type PostApiMembersIdClaimMutationError =
  | ApiResponse
  | ApiResponse
  | ApiResponse
  | ApiResponse;

/**
 * @summary 認領成員（綁定當前使用者）
 */
export const usePostApiMembersIdClaim = <
  TError = ApiResponse | ApiResponse | ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiMembersIdClaim>>,
      TError,
      { id: string; data: ClaimMemberDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiMembersIdClaim>>,
  TError,
  { id: string; data: ClaimMemberDto },
  TContext
> => {
  const mutationOptions = getPostApiMembersIdClaimMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 取消認領成員
 */
export const deleteApiMembersIdClaim = (id: string) => {
  return axiosInstance<void>({
    url: `/api/members/${id}/claim`,
    method: "DELETE",
  });
};

export const getDeleteApiMembersIdClaimMutationOptions = <
  TError = ApiResponse | ApiResponse | ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiMembersIdClaim>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiMembersIdClaim>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiMembersIdClaim"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiMembersIdClaim>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiMembersIdClaim(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiMembersIdClaimMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiMembersIdClaim>>
>;

export type DeleteApiMembersIdClaimMutationError =
  | ApiResponse
  | ApiResponse
  | ApiResponse
  | ApiResponse;

/**
 * @summary 取消認領成員
 */
export const useDeleteApiMembersIdClaim = <
  TError = ApiResponse | ApiResponse | ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiMembersIdClaim>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiMembersIdClaim>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiMembersIdClaimMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
