/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  ApiResponse,
  ClaimMemberDto,
  ClaimMemberResultDtoApiResponse,
  CreateMemberDto,
  MemberDtoApiResponse,
  UpdateMemberDto,
} from "../../models";

import { customInstance } from "../../../shared/lib/axios-instance";

/**
 * @summary 新增成員到帳單
 */
export const postApiSnapSplitBillsBillIdMembers = (
  billId: string,
  createMemberDto: CreateMemberDto,
  signal?: AbortSignal,
) => {
  return customInstance<MemberDtoApiResponse>({
    url: `/api/snap-split/bills/${billId}/members`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createMemberDto,
    signal,
  });
};

export const getPostApiSnapSplitBillsBillIdMembersMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdMembers>>,
    TError,
    { billId: string; data: CreateMemberDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdMembers>>,
  TError,
  { billId: string; data: CreateMemberDto },
  TContext
> => {
  const mutationKey = ["postApiSnapSplitBillsBillIdMembers"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdMembers>>,
    { billId: string; data: CreateMemberDto }
  > = (props) => {
    const { billId, data } = props ?? {};

    return postApiSnapSplitBillsBillIdMembers(billId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiSnapSplitBillsBillIdMembersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdMembers>>
>;
export type PostApiSnapSplitBillsBillIdMembersMutationBody = CreateMemberDto;
export type PostApiSnapSplitBillsBillIdMembersMutationError =
  | ApiResponse
  | ApiResponse;

/**
 * @summary 新增成員到帳單
 */
export const usePostApiSnapSplitBillsBillIdMembers = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdMembers>>,
      TError,
      { billId: string; data: CreateMemberDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiSnapSplitBillsBillIdMembers>>,
  TError,
  { billId: string; data: CreateMemberDto },
  TContext
> => {
  const mutationOptions =
    getPostApiSnapSplitBillsBillIdMembersMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 更新成員
 */
export const putApiSnapSplitMembersId = (
  id: string,
  updateMemberDto: UpdateMemberDto,
) => {
  return customInstance<MemberDtoApiResponse>({
    url: `/api/snap-split/members/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateMemberDto,
  });
};

export const getPutApiSnapSplitMembersIdMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiSnapSplitMembersId>>,
    TError,
    { id: string; data: UpdateMemberDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiSnapSplitMembersId>>,
  TError,
  { id: string; data: UpdateMemberDto },
  TContext
> => {
  const mutationKey = ["putApiSnapSplitMembersId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiSnapSplitMembersId>>,
    { id: string; data: UpdateMemberDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiSnapSplitMembersId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiSnapSplitMembersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiSnapSplitMembersId>>
>;
export type PutApiSnapSplitMembersIdMutationBody = UpdateMemberDto;
export type PutApiSnapSplitMembersIdMutationError = ApiResponse;

/**
 * @summary 更新成員
 */
export const usePutApiSnapSplitMembersId = <
  TError = ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiSnapSplitMembersId>>,
      TError,
      { id: string; data: UpdateMemberDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiSnapSplitMembersId>>,
  TError,
  { id: string; data: UpdateMemberDto },
  TContext
> => {
  const mutationOptions = getPutApiSnapSplitMembersIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 刪除成員
 */
export const deleteApiSnapSplitMembersId = (id: string) => {
  return customInstance<void>({
    url: `/api/snap-split/members/${id}`,
    method: "DELETE",
  });
};

export const getDeleteApiSnapSplitMembersIdMutationOptions = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiSnapSplitMembersId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiSnapSplitMembersId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiSnapSplitMembersId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiSnapSplitMembersId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiSnapSplitMembersId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiSnapSplitMembersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiSnapSplitMembersId>>
>;

export type DeleteApiSnapSplitMembersIdMutationError =
  | ApiResponse
  | ApiResponse;

/**
 * @summary 刪除成員
 */
export const useDeleteApiSnapSplitMembersId = <
  TError = ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiSnapSplitMembersId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiSnapSplitMembersId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getDeleteApiSnapSplitMembersIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 認領成員（綁定當前使用者）
 */
export const postApiSnapSplitMembersIdClaim = (
  id: string,
  claimMemberDto: ClaimMemberDto,
  signal?: AbortSignal,
) => {
  return customInstance<ClaimMemberResultDtoApiResponse>({
    url: `/api/snap-split/members/${id}/claim`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: claimMemberDto,
    signal,
  });
};

export const getPostApiSnapSplitMembersIdClaimMutationOptions = <
  TError = ApiResponse | ApiResponse | ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiSnapSplitMembersIdClaim>>,
    TError,
    { id: string; data: ClaimMemberDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiSnapSplitMembersIdClaim>>,
  TError,
  { id: string; data: ClaimMemberDto },
  TContext
> => {
  const mutationKey = ["postApiSnapSplitMembersIdClaim"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiSnapSplitMembersIdClaim>>,
    { id: string; data: ClaimMemberDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return postApiSnapSplitMembersIdClaim(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiSnapSplitMembersIdClaimMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiSnapSplitMembersIdClaim>>
>;
export type PostApiSnapSplitMembersIdClaimMutationBody = ClaimMemberDto;
export type PostApiSnapSplitMembersIdClaimMutationError =
  | ApiResponse
  | ApiResponse
  | ApiResponse
  | ApiResponse;

/**
 * @summary 認領成員（綁定當前使用者）
 */
export const usePostApiSnapSplitMembersIdClaim = <
  TError = ApiResponse | ApiResponse | ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiSnapSplitMembersIdClaim>>,
      TError,
      { id: string; data: ClaimMemberDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiSnapSplitMembersIdClaim>>,
  TError,
  { id: string; data: ClaimMemberDto },
  TContext
> => {
  const mutationOptions =
    getPostApiSnapSplitMembersIdClaimMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 取消認領成員
 */
export const deleteApiSnapSplitMembersIdClaim = (id: string) => {
  return customInstance<void>({
    url: `/api/snap-split/members/${id}/claim`,
    method: "DELETE",
  });
};

export const getDeleteApiSnapSplitMembersIdClaimMutationOptions = <
  TError = ApiResponse | ApiResponse | ApiResponse | ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiSnapSplitMembersIdClaim>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiSnapSplitMembersIdClaim>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiSnapSplitMembersIdClaim"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiSnapSplitMembersIdClaim>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiSnapSplitMembersIdClaim(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiSnapSplitMembersIdClaimMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiSnapSplitMembersIdClaim>>
>;

export type DeleteApiSnapSplitMembersIdClaimMutationError =
  | ApiResponse
  | ApiResponse
  | ApiResponse
  | ApiResponse;

/**
 * @summary 取消認領成員
 */
export const useDeleteApiSnapSplitMembersIdClaim = <
  TError = ApiResponse | ApiResponse | ApiResponse | ApiResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiSnapSplitMembersIdClaim>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiSnapSplitMembersIdClaim>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getDeleteApiSnapSplitMembersIdClaimMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
