/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */
import type { BillDto } from "./billDto";
import type { ErrorInfo } from "./errorInfo";

export interface BillDtoIReadOnlyListApiResponse {
  success?: boolean;
  /** @nullable */
  data?: BillDto[] | null;
  error?: ErrorInfo;
}
