/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */

export interface ClaimMemberResultDto {
  memberId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  originalName?: string | null;
  linkedUserId?: string;
  /** @nullable */
  linkedUserDisplayName?: string | null;
  /** @nullable */
  linkedUserAvatarUrl?: string | null;
  claimedAt?: string;
}
