/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */
import type { ClaimMemberResultDto } from "./claimMemberResultDto";
import type { ErrorInfo } from "./errorInfo";

export interface ClaimMemberResultDtoApiResponse {
  success?: boolean;
  data?: ClaimMemberResultDto;
  error?: ErrorInfo;
}
