/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * URL Shortener API
 * 短網址服務 API
 * OpenAPI spec version: v1
 */
import type { DateOnly } from "./dateOnly";

export interface ClicksByDateDto {
  date?: DateOnly;
  count?: number;
}
