/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * URL Shortener API
 * 短網址服務 API
 * OpenAPI spec version: v1
 */
import type { DayOfWeek } from "./dayOfWeek";

export interface DateOnly {
  year?: number;
  month?: number;
  day?: number;
  dayOfWeek?: DayOfWeek;
  readonly dayOfYear?: number;
  readonly dayNumber?: number;
}
