/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */
import type { DeltaIdMappingsDto } from "./deltaIdMappingsDto";
import type { ConflictInfo } from "./conflictInfo";
import type { BillDto } from "./billDto";

export interface DeltaSyncResponse {
  success?: boolean;
  newVersion?: number;
  idMappings?: DeltaIdMappingsDto;
  /** @nullable */
  conflicts?: ConflictInfo[] | null;
  mergedBill?: BillDto;
}
