/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Common API
 * 共用 API（認證、健康檢查）
 * OpenAPI spec version: v1
 */
import type { ErrorInfoDetails } from "./errorInfoDetails";

export interface ErrorInfo {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  details?: ErrorInfoDetails;
}
