/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */
import type { ExpenseDto } from "./expenseDto";
import type { ErrorInfo } from "./errorInfo";

export interface ExpenseDtoApiResponse {
  success?: boolean;
  data?: ExpenseDto;
  error?: ErrorInfo;
}
