/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */

export interface ExpenseItemUpdateDto {
  remoteId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  amount?: number | null;
  /** @nullable */
  paidByMemberId?: string | null;
  /** @nullable */
  participantIds?: string[] | null;
}
