/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Common API
 * 共用 API（認證、健康檢查）
 * OpenAPI spec version: v1
 */

export type GetApiAuthGoogleUrlParams = {
  /**
   * 登入成功後的重導向 URL
   */
  redirectUri?: string;
};
