/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Common API
 * 共用 API（認證、健康檢查）
 * OpenAPI spec version: v1
 */

export interface GoogleLoginRequestDto {
  /** @nullable */
  code?: string | null;
}
