/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * URL Shortener API
 * 短網址服務 API
 * OpenAPI spec version: v1
 */
import type { ShortUrlSummaryDto } from "./shortUrlSummaryDto";
import type { ErrorInfo } from "./errorInfo";

export interface ShortUrlSummaryDtoIReadOnlyListApiResponse {
  success?: boolean;
  /** @nullable */
  data?: ShortUrlSummaryDto[] | null;
  error?: ErrorInfo;
}
