/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * URL Shortener API
 * 短網址服務 API
 * OpenAPI spec version: v1
 */

export interface ShortUrlSummaryDto {
  id?: string;
  /** @nullable */
  shortCode?: string | null;
  /** @nullable */
  shortUrl?: string | null;
  clickCount?: number;
  createdAt?: string;
  isActive?: boolean;
  isExpired?: boolean;
}
