/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * URL Shortener API
 * 短網址服務 API
 * OpenAPI spec version: v1
 */
import type { ShortUrlDto } from "./shortUrlDto";
import type { ErrorInfo } from "./errorInfo";

export interface ShortUrlDtoApiResponse {
  success?: boolean;
  data?: ShortUrlDto;
  error?: ErrorInfo;
}
