/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */
import type { SyncIdMappingsDtoMembers } from "./syncIdMappingsDtoMembers";
import type { SyncIdMappingsDtoExpenses } from "./syncIdMappingsDtoExpenses";
import type { SyncIdMappingsDtoExpenseItems } from "./syncIdMappingsDtoExpenseItems";

export interface SyncIdMappingsDto {
  /** @nullable */
  members?: SyncIdMappingsDtoMembers;
  /** @nullable */
  expenses?: SyncIdMappingsDtoExpenses;
  /** @nullable */
  expenseItems?: SyncIdMappingsDtoExpenseItems;
}
