/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */
import type { SyncIdMappingsDto } from "./syncIdMappingsDto";
import type { BillDto } from "./billDto";

export interface SyncBillResponseDto {
  remoteId?: string;
  version?: number;
  /** @nullable */
  shareCode?: string | null;
  idMappings?: SyncIdMappingsDto;
  serverTimestamp?: string;
  latestBill?: BillDto;
}
