/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */

export interface TransferDto {
  fromMemberId?: string;
  /** @nullable */
  fromMemberName?: string | null;
  toMemberId?: string;
  /** @nullable */
  toMemberName?: string | null;
  amount?: number;
  isSettled?: boolean;
}
