/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SnapSplit API
 * 分帳計算與即時同步 API
 * OpenAPI spec version: v1
 */
import type { CreateExpenseItemDto } from "./createExpenseItemDto";

export interface UpdateExpenseDto {
  /** @nullable */
  name?: string | null;
  amount?: number;
  serviceFeePercent?: number;
  /** @nullable */
  paidById?: string | null;
  /** @nullable */
  participantIds?: string[] | null;
  /** @nullable */
  items?: CreateExpenseItemDto[] | null;
}
