/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * URL Shortener API
 * 短網址服務 API
 * OpenAPI spec version: v1
 */
import type { ClicksByDateDto } from "./clicksByDateDto";
import type { ClicksByReferrerDto } from "./clicksByReferrerDto";
import type { ClicksByDeviceDto } from "./clicksByDeviceDto";

export interface UrlStatsDto {
  shortUrlId?: string;
  /** @nullable */
  shortCode?: string | null;
  totalClicks?: number;
  /** @nullable */
  lastClickAt?: string | null;
  /** @nullable */
  clicksByDate?: ClicksByDateDto[] | null;
  /** @nullable */
  topReferrers?: ClicksByReferrerDto[] | null;
  /** @nullable */
  deviceBreakdown?: ClicksByDeviceDto[] | null;
}
