/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Common API
 * 共用 API（認證、健康檢查）
 * OpenAPI spec version: v1
 */

export interface UserDto {
  id?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
}
