/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Common API
 * 共用 API（認證、健康檢查）
 * OpenAPI spec version: v1
 */
import type { UserDto } from "./userDto";
import type { ErrorInfo } from "./errorInfo";

export interface UserDtoApiResponse {
  success?: boolean;
  data?: UserDto;
  error?: ErrorInfo;
}
