/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { ProblemDetails } from "../../models";

import { axiosInstance } from "../../axios-instance";

/**
 * 使用 302 Found（非 301）避免瀏覽器快取導致 Analytics 失真
 * @summary 轉址到原始 URL
 */
export const getShortCode = (shortCode: string, signal?: AbortSignal) => {
  return axiosInstance<unknown>({
    url: `/${shortCode}`,
    method: "GET",
    signal,
  });
};

export const getGetShortCodeQueryKey = (shortCode?: string) => {
  return [`/${shortCode}`] as const;
};

export const getGetShortCodeQueryOptions = <
  TData = Awaited<ReturnType<typeof getShortCode>>,
  TError = void | ProblemDetails | ProblemDetails,
>(
  shortCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getShortCode>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetShortCodeQueryKey(shortCode);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getShortCode>>> = ({
    signal,
  }) => getShortCode(shortCode, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!shortCode,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getShortCode>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetShortCodeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getShortCode>>
>;
export type GetShortCodeQueryError = void | ProblemDetails | ProblemDetails;

export function useGetShortCode<
  TData = Awaited<ReturnType<typeof getShortCode>>,
  TError = void | ProblemDetails | ProblemDetails,
>(
  shortCode: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getShortCode>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShortCode>>,
          TError,
          Awaited<ReturnType<typeof getShortCode>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetShortCode<
  TData = Awaited<ReturnType<typeof getShortCode>>,
  TError = void | ProblemDetails | ProblemDetails,
>(
  shortCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getShortCode>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShortCode>>,
          TError,
          Awaited<ReturnType<typeof getShortCode>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetShortCode<
  TData = Awaited<ReturnType<typeof getShortCode>>,
  TError = void | ProblemDetails | ProblemDetails,
>(
  shortCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getShortCode>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 轉址到原始 URL
 */

export function useGetShortCode<
  TData = Awaited<ReturnType<typeof getShortCode>>,
  TError = void | ProblemDetails | ProblemDetails,
>(
  shortCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getShortCode>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetShortCodeQueryOptions(shortCode, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
