/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiResponse,
  CreateShortUrlDto,
  GetApiUrlsIdStatsParams,
  ShortUrlDtoApiResponse,
  ShortUrlSummaryDtoIReadOnlyListApiResponse,
  UpdateShortUrlDto,
  UrlStatsDtoApiResponse,
} from "../../models";

import { axiosInstance } from "../../axios-instance";

/**
 * @summary 建立短網址
 */
export const postApiUrls = (
  createShortUrlDto: CreateShortUrlDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<ShortUrlDtoApiResponse>({
    url: `/api/urls`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createShortUrlDto,
    signal,
  });
};

export const getPostApiUrlsMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiUrls>>,
    TError,
    { data: CreateShortUrlDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiUrls>>,
  TError,
  { data: CreateShortUrlDto },
  TContext
> => {
  const mutationKey = ["postApiUrls"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiUrls>>,
    { data: CreateShortUrlDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiUrls(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiUrlsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiUrls>>
>;
export type PostApiUrlsMutationBody = CreateShortUrlDto;
export type PostApiUrlsMutationError = ApiResponse;

/**
 * @summary 建立短網址
 */
export const usePostApiUrls = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiUrls>>,
      TError,
      { data: CreateShortUrlDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiUrls>>,
  TError,
  { data: CreateShortUrlDto },
  TContext
> => {
  const mutationOptions = getPostApiUrlsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 取得目前使用者的所有短網址（需登入）
 */
export const getApiUrls = (signal?: AbortSignal) => {
  return axiosInstance<ShortUrlSummaryDtoIReadOnlyListApiResponse>({
    url: `/api/urls`,
    method: "GET",
    signal,
  });
};

export const getGetApiUrlsQueryKey = () => {
  return [`/api/urls`] as const;
};

export const getGetApiUrlsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiUrls>>,
  TError = ApiResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiUrls>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiUrlsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUrls>>> = ({
    signal,
  }) => getApiUrls(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiUrls>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUrlsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiUrls>>
>;
export type GetApiUrlsQueryError = ApiResponse;

export function useGetApiUrls<
  TData = Awaited<ReturnType<typeof getApiUrls>>,
  TError = ApiResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUrls>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUrls>>,
          TError,
          Awaited<ReturnType<typeof getApiUrls>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiUrls<
  TData = Awaited<ReturnType<typeof getApiUrls>>,
  TError = ApiResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUrls>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUrls>>,
          TError,
          Awaited<ReturnType<typeof getApiUrls>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiUrls<
  TData = Awaited<ReturnType<typeof getApiUrls>>,
  TError = ApiResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUrls>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 取得目前使用者的所有短網址（需登入）
 */

export function useGetApiUrls<
  TData = Awaited<ReturnType<typeof getApiUrls>>,
  TError = ApiResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUrls>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiUrlsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 根據 ID 取得短網址
 */
export const getApiUrlsId = (id: string, signal?: AbortSignal) => {
  return axiosInstance<ShortUrlDtoApiResponse>({
    url: `/api/urls/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiUrlsIdQueryKey = (id?: string) => {
  return [`/api/urls/${id}`] as const;
};

export const getGetApiUrlsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiUrlsId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUrlsId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiUrlsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUrlsId>>> = ({
    signal,
  }) => getApiUrlsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiUrlsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUrlsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiUrlsId>>
>;
export type GetApiUrlsIdQueryError = ApiResponse;

export function useGetApiUrlsId<
  TData = Awaited<ReturnType<typeof getApiUrlsId>>,
  TError = ApiResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUrlsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUrlsId>>,
          TError,
          Awaited<ReturnType<typeof getApiUrlsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiUrlsId<
  TData = Awaited<ReturnType<typeof getApiUrlsId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUrlsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUrlsId>>,
          TError,
          Awaited<ReturnType<typeof getApiUrlsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiUrlsId<
  TData = Awaited<ReturnType<typeof getApiUrlsId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUrlsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 根據 ID 取得短網址
 */

export function useGetApiUrlsId<
  TData = Awaited<ReturnType<typeof getApiUrlsId>>,
  TError = ApiResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUrlsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiUrlsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 更新短網址
 */
export const putApiUrlsId = (
  id: string,
  updateShortUrlDto: UpdateShortUrlDto,
) => {
  return axiosInstance<ShortUrlDtoApiResponse>({
    url: `/api/urls/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateShortUrlDto,
  });
};

export const getPutApiUrlsIdMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiUrlsId>>,
    TError,
    { id: string; data: UpdateShortUrlDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiUrlsId>>,
  TError,
  { id: string; data: UpdateShortUrlDto },
  TContext
> => {
  const mutationKey = ["putApiUrlsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiUrlsId>>,
    { id: string; data: UpdateShortUrlDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiUrlsId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiUrlsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiUrlsId>>
>;
export type PutApiUrlsIdMutationBody = UpdateShortUrlDto;
export type PutApiUrlsIdMutationError = ApiResponse;

/**
 * @summary 更新短網址
 */
export const usePutApiUrlsId = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiUrlsId>>,
      TError,
      { id: string; data: UpdateShortUrlDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiUrlsId>>,
  TError,
  { id: string; data: UpdateShortUrlDto },
  TContext
> => {
  const mutationOptions = getPutApiUrlsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 刪除短網址
 */
export const deleteApiUrlsId = (id: string) => {
  return axiosInstance<void>({ url: `/api/urls/${id}`, method: "DELETE" });
};

export const getDeleteApiUrlsIdMutationOptions = <
  TError = ApiResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiUrlsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiUrlsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiUrlsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiUrlsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiUrlsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiUrlsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiUrlsId>>
>;

export type DeleteApiUrlsIdMutationError = ApiResponse;

/**
 * @summary 刪除短網址
 */
export const useDeleteApiUrlsId = <TError = ApiResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiUrlsId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiUrlsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiUrlsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 取得短網址統計
 */
export const getApiUrlsIdStats = (
  id: string,
  params?: GetApiUrlsIdStatsParams,
  signal?: AbortSignal,
) => {
  return axiosInstance<UrlStatsDtoApiResponse>({
    url: `/api/urls/${id}/stats`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiUrlsIdStatsQueryKey = (
  id?: string,
  params?: GetApiUrlsIdStatsParams,
) => {
  return [`/api/urls/${id}/stats`, ...(params ? [params] : [])] as const;
};

export const getGetApiUrlsIdStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiUrlsIdStats>>,
  TError = ApiResponse,
>(
  id: string,
  params?: GetApiUrlsIdStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiUrlsIdStats>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiUrlsIdStatsQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiUrlsIdStats>>
  > = ({ signal }) => getApiUrlsIdStats(id, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiUrlsIdStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUrlsIdStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiUrlsIdStats>>
>;
export type GetApiUrlsIdStatsQueryError = ApiResponse;

export function useGetApiUrlsIdStats<
  TData = Awaited<ReturnType<typeof getApiUrlsIdStats>>,
  TError = ApiResponse,
>(
  id: string,
  params: undefined | GetApiUrlsIdStatsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiUrlsIdStats>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUrlsIdStats>>,
          TError,
          Awaited<ReturnType<typeof getApiUrlsIdStats>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiUrlsIdStats<
  TData = Awaited<ReturnType<typeof getApiUrlsIdStats>>,
  TError = ApiResponse,
>(
  id: string,
  params?: GetApiUrlsIdStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiUrlsIdStats>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUrlsIdStats>>,
          TError,
          Awaited<ReturnType<typeof getApiUrlsIdStats>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiUrlsIdStats<
  TData = Awaited<ReturnType<typeof getApiUrlsIdStats>>,
  TError = ApiResponse,
>(
  id: string,
  params?: GetApiUrlsIdStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiUrlsIdStats>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 取得短網址統計
 */

export function useGetApiUrlsIdStats<
  TData = Awaited<ReturnType<typeof getApiUrlsIdStats>>,
  TError = ApiResponse,
>(
  id: string,
  params?: GetApiUrlsIdStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiUrlsIdStats>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiUrlsIdStatsQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
