/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { ApiResponseData } from "./apiResponseData";
import type { ErrorInfo } from "./errorInfo";

export interface ApiResponse {
  success?: boolean;
  /** @nullable */
  data?: ApiResponseData;
  error?: ErrorInfo;
}
