/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { MemberDto } from "./memberDto";
import type { ExpenseDto } from "./expenseDto";

export interface BillDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  shareCode?: string | null;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  members?: MemberDto[] | null;
  /** @nullable */
  expenses?: ExpenseDto[] | null;
}
