/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { CreateExpenseItemDto } from "./createExpenseItemDto";

export interface CreateExpenseDto {
  /** @nullable */
  name?: string | null;
  amount?: number;
  serviceFeePercent?: number;
  isItemized?: boolean;
  /** @nullable */
  paidById?: string | null;
  /** @nullable */
  participantIds?: string[] | null;
  /** @nullable */
  items?: CreateExpenseItemDto[] | null;
}
