/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */

export interface DeltaSettlementDto {
  /** @nullable */
  fromMemberId?: string | null;
  /** @nullable */
  toMemberId?: string | null;
  amount?: number;
}
