/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { DeltaIdMappingsDtoMembers } from "./deltaIdMappingsDtoMembers";
import type { DeltaIdMappingsDtoExpenses } from "./deltaIdMappingsDtoExpenses";
import type { DeltaIdMappingsDtoExpenseItems } from "./deltaIdMappingsDtoExpenseItems";

export interface DeltaIdMappingsDto {
  /** @nullable */
  members?: DeltaIdMappingsDtoMembers;
  /** @nullable */
  expenses?: DeltaIdMappingsDtoExpenses;
  /** @nullable */
  expenseItems?: DeltaIdMappingsDtoExpenseItems;
}
