/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { DeltaSyncResponse } from "./deltaSyncResponse";
import type { ErrorInfo } from "./errorInfo";

export interface DeltaSyncResponseApiResponse {
  success?: boolean;
  data?: DeltaSyncResponse;
  error?: ErrorInfo;
}
