/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { ErrorInfoDetails } from "./errorInfoDetails";

export interface ErrorInfo {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  details?: ErrorInfoDetails;
}
