/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { ExpenseAddDto } from "./expenseAddDto";
import type { ExpenseUpdateDto } from "./expenseUpdateDto";

export interface ExpenseChangesDto {
  /** @nullable */
  add?: ExpenseAddDto[] | null;
  /** @nullable */
  update?: ExpenseUpdateDto[] | null;
  /** @nullable */
  delete?: string[] | null;
}
