/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { ExpenseDto } from "./expenseDto";
import type { ErrorInfo } from "./errorInfo";

export interface ExpenseDtoApiResponse {
  success?: boolean;
  data?: ExpenseDto;
  error?: ErrorInfo;
}
