/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */

export interface ExpenseItemDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  amount?: number;
  paidById?: string;
  /** @nullable */
  participantIds?: string[] | null;
}
