/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { ExpenseItemAddDto } from "./expenseItemAddDto";
import type { ExpenseItemUpdateDto } from "./expenseItemUpdateDto";

export interface ExpenseItemChangesDto {
  /** @nullable */
  add?: ExpenseItemAddDto[] | null;
  /** @nullable */
  update?: ExpenseItemUpdateDto[] | null;
  /** @nullable */
  delete?: string[] | null;
}
