/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */

export type GetApiAuthLineUrlParams = {
  /**
   * 登入成功後的重導向 URL
   */
  redirectUri?: string;
};
