/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { MemberDto } from "./memberDto";
import type { ErrorInfo } from "./errorInfo";

export interface MemberDtoApiResponse {
  success?: boolean;
  data?: MemberDto;
  error?: ErrorInfo;
}
