/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */

export interface MemberBalanceDto {
  memberId?: string;
  /** @nullable */
  memberName?: string | null;
  totalPaid?: number;
  totalOwed?: number;
  balance?: number;
}
