/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */

export interface MemberUpdateDto {
  remoteId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  displayOrder?: number | null;
  /** @nullable */
  linkedUserId?: string | null;
  /** @nullable */
  claimedAt?: string | null;
}
