/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { MemberBalanceDto } from "./memberBalanceDto";
import type { TransferDto } from "./transferDto";

export interface SettlementResultDto {
  totalAmount?: number;
  totalWithServiceFee?: number;
  /** @nullable */
  memberBalances?: MemberBalanceDto[] | null;
  /** @nullable */
  transfers?: TransferDto[] | null;
}
