/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { SettlementResultDto } from "./settlementResultDto";
import type { ErrorInfo } from "./errorInfo";

export interface SettlementResultDtoApiResponse {
  success?: boolean;
  data?: SettlementResultDto;
  error?: ErrorInfo;
}
