/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { ShortUrlSummaryDto } from "./shortUrlSummaryDto";
import type { ErrorInfo } from "./errorInfo";

export interface ShortUrlSummaryDtoIReadOnlyListApiResponse {
  success?: boolean;
  /** @nullable */
  data?: ShortUrlSummaryDto[] | null;
  error?: ErrorInfo;
}
