/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */

export interface ShortUrlDto {
  id?: string;
  /** @nullable */
  originalUrl?: string | null;
  /** @nullable */
  shortCode?: string | null;
  /** @nullable */
  shortUrl?: string | null;
  clickCount?: number;
  /** @nullable */
  expiresAt?: string | null;
  isActive?: boolean;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
}
