/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */

export interface SyncExpenseItemDto {
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  remoteId?: string | null;
  /** @nullable */
  name?: string | null;
  amount?: number;
  /** @nullable */
  paidByLocalId?: string | null;
  /** @nullable */
  participantLocalIds?: string[] | null;
}
