/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { SyncExpenseDto } from "./syncExpenseDto";

export interface SyncExpenseCollectionDto {
  /** @nullable */
  upsert?: SyncExpenseDto[] | null;
  /** @nullable */
  deletedIds?: string[] | null;
}
