/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { SyncExpenseItemDto } from "./syncExpenseItemDto";

export interface SyncExpenseItemCollectionDto {
  /** @nullable */
  upsert?: SyncExpenseItemDto[] | null;
  /** @nullable */
  deletedIds?: string[] | null;
}
