/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */
import type { SyncMemberDto } from "./syncMemberDto";
import type { SyncExpenseDto } from "./syncExpenseDto";

export interface SyncBillRequestDto {
  /** @nullable */
  remoteId?: string | null;
  /** @nullable */
  localId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  members?: SyncMemberDto[] | null;
  /** @nullable */
  expenses?: SyncExpenseDto[] | null;
  /** @nullable */
  settledTransfers?: string[] | null;
  localUpdatedAt?: string;
}
