/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type SyncIdMappingsDtoExpenses = { [key: string]: string } | null;
