/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * KaydenTools API
 * KaydenTools Backend API - SnapSplit, Authentication, and more.
 * OpenAPI spec version: v1
 */

export interface TransferDto {
  fromMemberId?: string;
  /** @nullable */
  fromMemberName?: string | null;
  toMemberId?: string;
  /** @nullable */
  toMemberName?: string | null;
  amount?: number;
  isSettled?: boolean;
}
